name: fangyuanxiaozhan
on:
  push:
    branches:    
      - main
jobs:
  push:
      runs-on: ubuntu-20.04
      steps:
      - uses: actions/checkout@v2 # Checking out the repo
      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d # Install all dependencies, including development ones
      - name: Test
        env:
            USERNAME: ${{ secrets.USERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run push # Run custom `test` command defined in the `[scripts]` block of Pipfile